import { ValidSkills } from "./constants";

export interface CareerExperienceInterface {
  id: string;
  position: string;
  company: string;
  location: string;
  startDate: Date;
  endDate: Date | "Present";
  description: string[];
  achievements: string[];
  skills: ValidSkills[];
  companyUrl?: string;
  logo?: string;
}

export const careerExperiences: CareerExperienceInterface[] = [
  {
    id: "megaleios",
    position: "Mobile Developer",
    company: "Megaleios",
    location: "São Paulo, São Paulo - Brazil",
    startDate: new Date("2024-08-01"),
    endDate: "Present",
    description: [
      "Application development from scratch and maintenance of existing applications",
      "Implementation of login screens, registration, forgot password, data registration and editing with photos, logout functionality",
      "Development of dynamic and paginated listings with registration, data editing and deletion, filters, bottom sheets, modals",
      "Creation of graphs and dashboards with animations, maps with geolocation and filters",
      "Implementation of payment method and card registration screens, interfaces with data change history",
      "Functionality and screen integrations with Backend REST APIs",
      "Feature integration with Google Maps",
      "Code refactoring and technical improvements to the architecture",
      "Integration with camera and photo gallery",
      "Implementation of responsive interfaces for mobile and tablet on Android and iOS",
      "Integration of payment screens with PIX",
      "Version publications and deployment in the Apple Store and Play Store and distribution in the Firebase console",
      "Development of AI-powered features for image recognition and automated content moderation",
      "Integration of machine learning models for user behavior analysis and personalized recommendations",
    ],
    achievements: [
      "Application development from scratch with modern mobile development practices",
      "Improved performance of dynamic listings and user experience, with the use of infinite scroll and pagination",
      "Addition of Pix as a payment method, integrating Iugu and using webhooks to ensure fast, secure, and real-time transactions",
      "Enhanced user experience by providing more payment options for the app",
      "Implemented AI-powered image recognition system improving content moderation by 40%",
      "Developed personalized recommendation engine using machine learning algorithms",
    ],
    skills: [
      "React Native",
      "Flutter",
      "Dart",
      "Javascript",
      "Typescript",
      "Firebase",
      "Google Maps API",
      "PIX",
      "Iugu",
      "OpenAI",
      "Model Integration",
      "Model Training",
    ],
  },
  {
    id: "rav-tecnologia",
    position: "Frontend Engineer",
    company: "Rav Tecnologia",
    location: "Fortaleza, Ceará - BR",
    startDate: new Date("2023-07-01"),
    endDate: new Date("2024-08-01"),
    description: [
      "Development of user interfaces and dashboards with React for a web system for monitoring networks and IoT technologies",
      "Development of features with Dart and Flutter for an application to monitor agricultural fields with IoT",
      "Database implementation with SQLite to store data in the application's offline mode",
      "Screen implementation with internet connection tests, power and location of transmission towers that use measurements with IoT",
      "Development of graphical interfaces with Recharts and React",
      "Navigation between interfaces with Next.js",
      "Documentation of test cases, unit tests and widget tests",
      "Generation of application notifications",
      "Presentation of completed activities related to the application in end-of-sprint meetings",
      "Implementation of password validations and security features",
      "Development of AI-powered predictive analytics dashboard for agricultural monitoring",
      "Integration of machine learning models for crop yield prediction and weather forecasting",
      "Built web-based AI agent for research and content generation using OpenAI APIs",
    ],
    achievements: [
      "Increased local data persistence by 2x by replacing local caching with SQLite database and rewriting the app's offline mode with Flutter",
      "Increased application test coverage by approximately 50%, implementing unit tests and widget tests with Flutter Test and Mocktail",
      "Adopted Clean Code Design Patterns to improve code maintainability and readability",
      "Developed AI-powered predictive analytics system improving crop yield predictions by 35%",
      "Built Skywork.ai - an AI research agent for content generation using OpenAI and LangChain",
      "Created Aluo.ai - AI-powered image editing platform with automated enhancement features",
    ],
    skills: [
      "React",
      "Flutter",
      "Dart",
      "Next.js",
      "SQLite",
      "Recharts",
      "IoT",
      "Clean Code",
      "Unit Testing",
      "Widget Testing",
      "OpenAI",
      "Model Integration",
      "Model Training",
      "LangChain",
    ],
  },
  {
    id: "full-stack-intern",
    position: "Full Stack Development Intern",
    company: "Industry Project",
    location: "Fortaleza, Ceará - BR",
    startDate: new Date("2022-10-01"),
    endDate: new Date("2023-07-01"),
    description: [
      "Worked on a web system that manages activities and plans projects for an industry through lists, schedules and graphs",
      "Development of screens and user interfaces with TypeScript, JavaScript, React and Next.js in Frontend",
      "Creating reusable components and styling interfaces with CSS modules and Styled Components",
      "Bug fixes in features, tests and improvements in application performance",
      "Discussion of activities with other interns, mutual help and joint resolution to accelerate project sprints",
      "Building REST APIs and request handling with Node.js and Express",
      "Database management, manipulation of entities and development of functions and logics in the Backend with Express, TypeORM and Oracle Database",
      "Development of Taxi1000 mobile application for local taxi services with real-time tracking",
      "Implementation of user authentication and payment processing systems",
      "Integration with Google Maps API for route optimization and driver tracking",
    ],
    achievements: [
      "Decreased the loading time of screens with large amounts of data by 90% by adjusting requests with Node.js and Express and optimizing with React",
      "Decreased by 3x the number of renderings of some components by using memoization hooks like useCallback and useMemo",
      "Reduced the use of hooks like useEffect and useState, which improved performance and user experience on the frontend",
      "Developed Taxi1000 mobile app improving local taxi service efficiency by 60%",
      "Implemented real-time tracking system reducing passenger wait times by 45%",
    ],
    skills: [
      "React",
      "Next.js",
      "Typescript",
      "Javascript",
      "Node.js",
      "Express",
      "TypeORM",
      "Oracle Database",
      "CSS Modules",
      "Styled Components",
      "Kotlin",
      "Firebase",
      "Django",
    ],
  },
  {
    id: "ufc",
    position: "Mobile Developer",
    company: "Universidade Federal do Ceará",
    location: "Fortaleza, Ceará - BR",
    startDate: new Date("2020-06-01"),
    endDate: new Date("2022-10-01"),
    description: [
      "Worked on a college extension mobile project that monitors the campus' internal bus through a tracker",
      "Developed features to offer bus routes, real-time location, waiting time at bus stops",
      "Created a university map with the location of blocks and key campus points",
      "Development of screens for routes and bus lines",
      "Integration of the application with Google Maps, use of its API and location of the main points within the internal campus",
      "Development of Absopure web system for recycling company in Peru",
      "Built Laravel-based application for recyclable materials management",
      "Implementation of payment processing with Stripe integration",
      "Created motion designer portfolio website with advanced animations",
      "Development of responsive web applications using modern frontend technologies",
    ],
    achievements: [
      "Developed a collaborative application with Flutter that helped more than 70% of the students interviewed",
      "Solved the problem of students not knowing how to locate the bus on campus, which was affecting their academic activities due to transportation delays",
      "Built Absopure recycling management system improving collection efficiency by 50%",
      "Developed motion designer portfolio with advanced animations and modern design",
      "Successfully deployed first production web application with Laravel and Firebase",
    ],
    skills: [
      "Flutter",
      "Dart",
      "Google Maps API",
      "Mobile Development",
      "Real-time Tracking",
      "Laravel",
      "PHP",
      "MySQL",
      "Next.js",
      "Tailwind CSS",
      "Firebase",
    ],
  },
];
