export const siteConfig = {
  name: "Renan Martins | Software Developer Portfolio",
  authorName: "Renan Martins",
  username: "renanmartins",
  description:
    "Renan Martin's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
  url: "https://renanmartins.dev",
  links: {
    linkedin: "https://www.linkedin.com/in/renanmdreis/",
    github: "https://github.com/renanmdreis45",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Renan Martins",
    "Full Stack Developer",
    "Software Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Software developer portfolio template",
    "Responsive portfolio template",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
